const friends=[
    {username:"James horis",rollno:1,image:"https://up.yimg.com/ib/th?id=OIP.IGNf7GuQaCqz_RPq5wCkPgAAAA&pid=Api&rs=1&c=1&qlt=95&w=78&h=117",post:"socialmedia/src/components/images/pexels-andrea-piacquadio-762080.jpg",title:"Do not scorn what you have received, nor envy the gains of others. He who envies others does not obtain peace of mind. "},
    {username:"Peter parkor",rollno:2,image:"https://up.yimg.com/ib/th?id=OIP.0l7k5zqRUVQ5Yq9eTpW2LgHaLJ&pid=Api&rs=1&c=1&qlt=95&w=78&h=117",post:"socialmedia/src/components/images/pexels-cami-20362303.jpg",title:"Know that although in the eternal scheme of things you are small, you are also unique and irreplaceable, as are all your fellow humans everywhere in the world. "},
    {username:"Tom holland",rollno:3,image:"https://up.yimg.com/ib/th?id=OIP.cive38eqp7C2RKVt4xkzbQHaLH&pid=Api&rs=1&c=1&qlt=95&w=78&h=117",post:"socialmedia/src/components/images/pexels-ines-martin-6200867.jpg",title:" No garden is without its weeds. "},
    {username:"Tobey maguare",rollno:4,image:"https://up.yimg.com/ib/th?id=OIP.lzECLwvnyWXogFBUYWQ4UAHaJQ&pid=Api&rs=1&c=1&qlt=95&w=94&h=117",post:"socialmedia/src/components/images/pexels-julia-filirovska-7138355.jpg",title:" Great acts are made up of small deeds. "},
    {username:"Andrew garfield",rollno:5,image:"https://up.yimg.com/ib/th?id=OIP.hCfHyL8u8XAbreXuaiTMQgHaHZ&pid=Api&rs=1&c=1&qlt=95&w=117&h=117",post:"socialmedia/src/components/images/pexels-kaique-rocha-307847.jpg",title:" Friendship is held to be the severest test of character. It is easy, we think, to be loyal to a family and clan, whose blood is in your own veins. "
},
    {username:"Peter Quel",rollno:6,image:"https://up.yimg.com/ib/th?id=OIP.XMJapQiW0_Q0aIWNxjIxoAAAAA&pid=Api&rs=1&c=1&qlt=95&w=70&h=105",post:"socialmedia/src/components/images/pexels-pixabay-39866.jpg",title:" The first requisite for success is the ability to apply your physical and mental energies to one problem incessantly without growing weary. "},
    {username:"Jack segal",rollno:7,image:"https://up.yimg.com/ib/th?id=OIP.Rv5hzhHxzYHGKELo5TzKFQHaLH&pid=Api&rs=1&c=1&qlt=95&w=70&h=105",post:"socialmedia/src/components/images/pexels-pixabay-301952.jpg",title:" Those who will play with cats must expect to be scratched. "},
    {username:"Robert downey",rollno:8,image:"https://up.yimg.com/ib/th?id=OIP.Xpwq3QyBT3rZbqJMEYfw1AAAAA&pid=Api&rs=1&c=1&qlt=95&w=76&h=114",post:"socialmedia/src/components/images/pexels-trinity-kubassek-445109.jpg",title:" My friends are my estate. "
},
    {username:"Bucky banes",rollno:9,image:"https://up.yimg.com/ib/th?id=OIP.Erm6-WQK5WXEAfsdA2wh6QHaKj&pid=Api&rs=1&c=1&qlt=95&w=85&h=122",post:"socialmedia/src/components/images/pexels-yu-zhang-20528016.jpg",title:" The art of progress is to preserve order amid change, and to preserve change amid order. "}
]

export default friends